name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # runner가 실행될 환경을 설정합니다.
    runs-on: ubuntu-latest

    steps:
      # 코드를 가져옵니다.
      - name: Checkout code
        uses: actions/checkout@v3

      # node 버전을 셋팅합니다.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.DEV_S3_BUCKET }} --delete
